---
# cmd: ansible-playbook -i hosts.txt playbook-pi.yml
# cmd: Test Ping:  ansible pi_host -i hosts.txt -m ping
#https://www.youtube.com/watch?v=MfoAb50Br94
- name: Deploy Capture Stream On RPI
  hosts: pi_host
  remote_user: root

  tasks:
    - name: Check if ffmpeg is installed
      become: yes
      shell: dpkg-query -W -f='${Status}' ffmpeg
      register: is_ffmpeg_installed

    - name: Install ffmpeg
      become: yes
      apt: name=ffmpeg state=present
      when: is_ffmpeg_installed.stdout.find('no packages found') != -1

    - name: Check if vim is installed
      become: yes
      shell: dpkg-query -W -f='${Status}' vim
      register: is_vim_installed

    - name: Install vim
      become: yes
      apt: name=vim state=present
      when: is_vim_installed.stdout.find('no packages found') != -1
      ignore_errors: True

    - name: Create directory
      file:
        path: /home/pi/capstonescript
        state: directory
        owner: pi
        group: pi
        mode: 0775
        
    - name: Install Streaming Program
      template: src={{item.src}} dest={{item.dest}}
      with_items:
        - {src: 'capstonevideostream/capturestream.py', dest: '/home/pi/capstonescript/capturestream.py' }
        - {src: '__main__.py', dest: '/home/pi/capstonescript/__main__.py' }
      notify:
        - Restart capstream

    - name: Install Service capture stream
      become: yes
      template: src='capstream.service' dest='/etc/systemd/system/capstream.service'

    - name: start capstream
      become: yes
      command: systemctl start capstream

    - name: Ensure capstream launches on boot
      become: yes
      command: systemctl enable capstream

  handlers:
    - name: Restart capstream
      become: yes
      command: systemctl restart capstream
