---
# cmd: ansible-playbook -i hosts.txt playbook-pi.yml
# cmd: Test Ping:  ansible pi_host -i hosts.txt -m ping
#https://www.youtube.com/watch?v=MfoAb50Br94
- name: Deploy Capture Stream On RPI
  hosts: pi_host
  remote_user: root

  tasks:
    - name: Install The IP Client
      template: src={{item.src}} dest={{item.dest}}
      with_items:
        - {src: '/home/erman/immersion/IpDisco-Prj/ip_disco_client/ip_disc_client.py', dest: '/home/pi/IpDisco-Prj/ip_disco_client/ip_disc_client.py' }
        - {src: '/home/erman/immersion/IpDisco-Prj/ip_disco_client/config/config_file.json', dest: '/home/pi/IpDisco-Prj/ip_disco_client/config/config_file.json' }
      notify:
        - Restart capstream

    - name: RUN IP CLIENTs
      become: yes
      shell: $(which python3) /home/pi/IpDisco-Prj/ip_disco_client/ip_disc_client.py

  handlers:
    - name: Restart capstream
      become: yes
      command: systemctl restart capstream
